import {AppProps} from "next/app"
import Head from "next/head"
import {CssBaseline, ThemeProvider} from "@mui/material"
import {theme} from "styles/theme"
import {GlobalStyle} from "styles/global-styles"
import {ToastContainer} from "react-toastify"
import "react-toastify/dist/ReactToastify.css"

function MyApp({Component, pageProps}: AppProps) {
    return (
        <>
            <Head>
                <title>Simbaat Shop</title>
                <meta name="description" content="Generated by create next app" />
                {/* favicon */}
                {/* font */}
                <link
                    href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square-round.css"
                    rel="stylesheet"
                ></link>
            </Head>
            <ThemeProvider theme={theme}>
                <CssBaseline />
                <GlobalStyle />
                <Component {...pageProps} />
                <ToastContainer autoClose={2000} pauseOnHover={false} hideProgressBar />
            </ThemeProvider>
        </>
    )
}

export default MyApp
