import {AppProps} from "next/app"
import Head from "next/head"
import {CssBaseline, ThemeProvider} from "@mui/material"
import {theme} from "styles/theme"
import {GlobalStyle} from "styles/global-styles"

function MyApp({Component, pageProps}: AppProps) {
    return (
        <>
            <Head>
                <title>Simbaat Shop</title>
                <meta name="description" content="Generated by create next app" />
                {/* favicon */}
                {/* font */}
                <link
                    rel="stylesheet"
                    type="text/css"
                    href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard-dynamic-subset.css"
                />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
            </Head>
            <ThemeProvider theme={theme}>
                <CssBaseline />
                <GlobalStyle />
                <Component {...pageProps} />
            </ThemeProvider>
        </>
    )
}

export default MyApp
